### ISSUE TITLE
Research possible approaches to speeding up dependencies portion of CI builds

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#1084]
# Problem

Our `circle.yml` does the following at time of writing:

```
dependencies:
  pre:
    - |
      if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
        curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
      fi
  cache_directories:
    - ~/.yarn
    - ~/.cache/yarn
    - /home/ubuntu/nvm/versions/node/v6.9.4/bin
    - /home/ubuntu/nvm/versions/node/v6.9.4/lib/node_modules
  override:
    - yarn global add bower
    - yarn global add phantomjs-prebuilt
    - yarn add node-sass
    - yarn install
    - bower install
```

The slowest steps of the `override` are as follows:
- `yarn global add bower` ~10s
- `yarn global add phantomjs-prebuilt` ~10s
- `yarn add node-sass` ~25s
- `yarn install` ~25s

Someone should research if there is any way to speed any of these steps up.
